

campos_cad = {'cidades': {'1': 'Santo Andre',
                          '2': 'Sao Bernardo do Campo'
                          },
              'entidades': {'1': 'CRAS SANTO ANDRE - CENTRO',
                            '2': 'CRAS SBC - CENTRO',
                            '3': 'CREAS SANTO ANDRE',
                            '4': 'CREAS SBC',
                            '5': 'GESTORA-SP'

                            },
              'etnias': {'1': 'Amarela',
                         '2': 'Branca',
                         '3': 'Índigena',
                         '4': 'Parda',
                         '5': 'Preta',
                         '6': 'Não informado'
                         },
              'identidades_genero': {'1': 'Agênero',
                                     '2': 'Cisgênero',
                                     '3': 'Não Binário',
                                     '4': 'Transgênero',
                                     'z': 'Não informado'
                                     },
              'orientacoes_sexual': {'1': 'Assexual',
                                     '2': 'Bissexual',
                                     '3': 'Heterossexual',
                                     '4': 'Homossexual',
                                     '5': 'Pansexual',
                                     '6': 'Não informado'
                                     },
              'questao_migracao': {'1': '1 - Motivos econômicos',
                                   '2': '2 - Motivos políticos',
                                   '3': '3 - Motivos de guerra',
                                   '4': '4 - Não',
                                   '5': '5 - Não respondeu'
                                   },

              'sexos': {'1': 'Feminino',
                        '2': 'Maculino',
                        '3': 'Não informado'
                        },
              'uf_s': {'ac': 'AC', 'al': 'AL', 'am': 'AM', 'ap': 'AP', 'ba': 'BA',
                       'ce': 'CE', 'df': 'DF', 'es': 'ES', 'go': 'GO', 'ma': 'MA',
                       'mg': 'MG', 'ms': 'MS', 'mt': 'MT', 'pa': 'PA', 'pb': 'PB',
                       'pe': 'PE', 'pi': 'PI', 'rj': 'RJ', 'rn': 'RN', 'ro': 'RO',
                       'rr': 'RR', 'rs': 'RS', 'sc': 'SC', 'se': 'SE', 'sp': 'SP',
                       'to': 'TO'}
              }

questionario = {'questao_1': {'1': '1 - Rua',
                              '2': '2 - Albergue',
                              '3': '3 - Domicílio particular',
                              '4': '4 - Outro',
                              '5': '5 - Não respondeu'
                              },
                'questao_2': {'1': '1 - Até seis meses',
                              '2': '2 - Entre seis meses e 1 ano',
                              '3': '3 - Entre 1 e 2 anos',
                              '4': '4 - Entre 2 e 5 anos',
                              '5': '5 - Entre 5 e 10 anos',
                              '6': '6 - Mais de 10 anos',
                              '7': '7 - Não respondeu'
                              },
                'questao_3': {'1': '1 - Perda de moradia',
                              '2': '2 - Ameaça / violência',
                              '3': '3 - Problemas com familiares / companheiro(a)',
                              '4': '4 - Alcoolismo / drogas',
                              '5': '5 - Desemprego',
                              '6': '6 - Trabalho',
                              '7': '7 - Tratamento de saúde',
                              '8': '8 - Preferência / opção própria',
                              '9': '9 - Outro',
                              '10': '10 - Não sabe / não se lembra',
                              '11': '11 - Não respondeu'
                              },
                'questao_4': {'1': '1 - Até seis meses',
                              '2': '2 - Entre seis meses e 1 ano',
                              '3': '3 - Entre 1 e 2 anos',
                              '4': '4 - Entre 2 e 5 anos',
                              '5': '5 - Entre 5 e 10 anos',
                              '6': '6 - Mais de 10 anos',
                              '7': '7 - Não respondeu'
                              },
                'questao_5': {'1': '1 - Sim',
                              '2': '2 - Não',
                              '3': '3 - Não respondeu'
                              },
                'questao_6': {'1': '1 - Todo dia',
                              '2': '2 - Toda semana',
                              '3': '3 - Todo mês',
                              '4': '4 - Todo ano',
                              '5': '5 - Quase nunca',
                              '6': '6 - Nunca',
                              '7': '7 - Não respondeu'
                              },
                'questao_7': {'1': '1 - Escola',
                              '2': '2 - Associação',
                              '3': '3 - Cooperativa',
                              '4': '4 - Movimento social',
                              '5': '5 - Não sabe / não se lembra',
                              '6': '6 - Não respondeu'
                              },
                'questao_8': {'1': '1 - Centro de Referência da Assistência Social - CRAS',
                              '2': '2 - Centro de Referência Especializado da Assistência Social - CREAS',
                              '3': '3 - Centro de Referência para População em Situação de Rua - Centro Pop',
                              '4': '4 - Instituição de Acolhimento Governamental (albergu/abrigo/outro)',
                              '5': '5 - Instituição de Acolhiimento Não-Governamental (institução beneficente privada/outro)',
                              '6': '6 - Hospital/clínica geral',
                              '7': '7 - Nenhum',
                              '8': '8 - Não respondeu'
                              },
                'questao_9': {'1': '1 - Sim',
                              '2': '2 - Não',
                              '3': '3 - Não sabe',
                              '4': '4 - Não respondeu'
                              },
                'questao_10': {'1': '1 - Construção civil',
                               '2': '2 - Guardador de carro / fileira',
                               '3': '3 - Carregador / estivador',
                               '4': '4 - Catador de material reciclável',
                               '5': '5 - Serviços gerais / limpeza / outros',
                               '6': '6 - Pede dinheiro',
                               '7': '7 - Vendas',
                               '8': '8 - Outro',
                               '9': '9 - Não respondeu',
                               },
                'questao_12': {'1': '1 - Até seis meses',
                               '2': '2 - Entre seis meses e 1 ano',
                               '3': '3 - Entre 1 e 2 anos',
                               '4': '4 - Entre 2 e 5 anos',
                               '5': '5 - Entre 5 e 10 anos',
                               '6': '6 - Mais de 10 anos',
                               '7': '7 - Não respondeu',
                               },
                'questao_13': {'1': '1 - Deficiência auditiva',
                               '2': '2 - Deficiência intelectual',
                               '3': '3 - Deficiência motora',
                               '4': '4 - Deficiência múltipla',
                               '5': '5 - Deficiência psicossocial',
                               '6': '6 - Deficiência visual',
                               '7': '7 - Outra deficiência',
                               '8': '8 - Não possui deficiência',
                               '9': '9 - Não respondeu'
                               },
                'questao_14': {'1': '1 - Sim, primeira dose',
                               '2': '2 - Sim, segunda dose',
                               '3': '3 - Sim, terceira dose (dose de reforço)',
                               '4': '4 - Não',
                               '5': '5 - Não respondeu'
                               }
                }
